database:
  duckdb_path: output/recruit.duckdb
  duckdb_threads: 32

job_title_parsing:
  catalog_table: recruit.main.chinese_occupational_dictionary_joined
  catalog_preprocessed_table: recruit.main.chinese_occupational_dictionary_joined_preprocessed
  jobs_table: gd_recruit_liepin_sample, gd_recruit_qcwy_sample, zhilian_guangdong_sample
  match_result_table: recruit.main.job_match_results

skill_extraction:
  requirement_match_table: recruit.main.skill_extraction_requirement_matches

raw_database: recruit.raw_data.lieping_raw_data, recruit.raw_data.qcwu_raw_data, recruit.raw_data.zhilian_raw_data

LLM_model_path: D:/model/Qwen3-8B
BERT_path: D:\model\chinese-roberta-wwm-ext
